Payloader
membraneframework/membrane_rtp_vp9_plugin pull request #6
Opened 2021-02-01 14:58 UTC by AndrzejPodo

2021-02-11 10:58 UTC, mat-hek requested changes

2021-02-11 10:58 UTC, mat-hek commented on lib/rtp_vp9/payload_descriptor.ex
> +      if ss.pg_descriptions do
this should always be list

2021-02-11 10:58 UTC, mat-hek commented on lib/rtp_vp9/payload_descriptor.ex
> +        do: payload_descriptor.p_diffs |> Enum.reduce(<<>>, &(&2 <> <<&1>>)),
use Enum.map_join

2021-02-11 10:58 UTC, mat-hek commented on lib/rtp_vp9/payload_descriptor.ex
> +      if pg_description.p_diffs do
this should always be list

2021-02-11 10:58 UTC, mat-hek commented on lib/rtp_vp9/payloader.ex
> +      |> Enum.map_reduce(1, fn chunk, i ->
using `|> List.update_at(-1, ...)` would make it more clear

2021-02-11 10:58 UTC, mat-hek commented on lib/rtp_vp9/payloader.ex
> +    [@first_fragment_descriptor <> first_chunk | Enum.reverse(chunks)]
these two clauses do pretty much the same thing, let's merge them

2021-02-11 10:58 UTC, mat-hek commented on lib/rtp_vp9/payloader.ex
> +        %Buffer{metadata: metadata, payload: payload},
let's do this match in the function body

2021-02-12 16:34 UTC, mat-hek commented on .gitignore
> +payloader_with_session_bin_test.exs
to remove

2021-02-12 16:34 UTC, mat-hek commented on lib/rtp_vp9/payload_descriptor.ex
> +    dimensions = ss.dimensions |> Enum.map_join("", &serialize(&1))
the empty string is the default joiner

2021-02-12 16:34 UTC, mat-hek commented on lib/rtp_vp9/payload_descriptor.ex
> +    n_g = length(ss.pg_descriptions)
```suggestion
    n_g = <<length(ss.pg_descriptions)>>
```

2021-02-12 16:34 UTC, mat-hek commented on lib/rtp_vp9/payloader.ex
> +        buffer,
all arguments will fit in a single line now

2021-02-12 16:34 UTC, mat-hek commented on lib/rtp_vp9/payloader.ex
>      max_chunk_size = ceil(byte_size(payload) / chunk_count)
doesn't this equal max_payload_size?

2021-03-05 11:20 UTC, AndrzejPodo commented on lib/rtp_vp9/payloader.ex
>      max_chunk_size = ceil(byte_size(payload) / chunk_count)
We discussed that in VP8 payloader.

2021-03-08 10:22 UTC, mat-hek approved these changes

2021-04-07 14:27 UTC, merged